# Enhanced docker-compose with monitoring and QoL improvements
version: "3.8"
services:
  asa-server-1:
    container_name: asa-server-1
    hostname: asa-server-1
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    tty: true
    restart: unless-stopped
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0
      - BACKUP_SCHEDULE=0 4 * * *  # Daily backup at 4 AM
      - BACKUP_RETENTION=7         # Keep 7 backups
    ports:
      # Game port for player connections through the server browser
      - 0.0.0.0:7777:7777/udp
      # RCON port for remote server administration
      - 0.0.0.0:27020:27020/tcp
    depends_on:
      set-permissions-1:
        condition: service_completed_successfully
    volumes:
      - steam-1:/home/gameserver/Steam:rw
      - steamcmd-1:/home/gameserver/steamcmd:rw
      - server-files-1:/home/gameserver/server-files:rw
      - cluster-shared:/home/gameserver/cluster-shared:rw
      - backups-1:/home/gameserver/backups:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      asa-network:
    # Health check to monitor server status
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'ArkAscendedServer.exe|AsaApiLoader.exe' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s  # Give server 5 minutes to start
    # Resource limits for better stability
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        
  set-permissions-1:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files ; chown -R 25000:25000 /cluster-shared ; chown -R 25000:25000 /backups'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam-1:/steam:rw
      - steamcmd-1:/steamcmd:rw
      - server-files-1:/server-files:rw
      - cluster-shared:/cluster-shared:rw
      - backups-1:/backups:rw

  # Optional: Monitoring container (uncomment to enable)
  # monitoring:
  #   container_name: asa-monitoring
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   ports:
  #     - 9100:9100
  #   networks:
  #     - asa-network

#  asa-server-2:
#    container_name: asa-server-2
#    hostname: asa-server-2
#    entrypoint: "/usr/bin/start_server"
#    user: gameserver
#    image: "mschnitzer/asa-linux-server:latest"
#    tty: true
#    restart: unless-stopped
#    environment:
#      - ASA_START_PARAMS=ScorchedEarth_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared"
#      - ENABLE_DEBUG=0
#      - BACKUP_SCHEDULE=0 4 * * *
#      - BACKUP_RETENTION=7
#    ports:
#      # Game port for player connections through the server browser
#      - 0.0.0.0:7778:7778/udp
#      # RCON port for remote server administration
#      - 0.0.0.0:27021:27021/tcp
#    depends_on:
#      set-permissions-2:
#        condition: service_completed_successfully
#    volumes:
#      - steam-2:/home/gameserver/Steam:rw
#      - steamcmd-2:/home/gameserver/steamcmd:rw
#      - server-files-2:/home/gameserver/server-files:rw
#      - cluster-shared:/home/gameserver/cluster-shared:rw
#      - backups-2:/home/gameserver/backups:rw
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      asa-network:
#    healthcheck:
#      test: ["CMD-SHELL", "pgrep -f 'ArkAscendedServer.exe|AsaApiLoader.exe' || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 300s
#    deploy:
#      resources:
#        limits:
#          memory: 16G
#        reservations:
#          memory: 8G
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "3"
#        
#  set-permissions-2:
#    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files ; chown -R 25000:25000 /cluster-shared ; chown -R 25000:25000 /backups'"
#    user: root
#    image: "opensuse/leap"
#    volumes:
#      - steam-2:/steam:rw
#      - steamcmd-2:/steamcmd:rw
#      - server-files-2:/server-files:rw
#      - cluster-shared:/cluster-shared:rw
#      - backups-2:/backups:rw

volumes:
  cluster-shared:
    name: asa-server_cluster-shared
  steam-1:
    name: asa-server_steam-1
  steamcmd-1:
    name: asa-server_steamcmd-1
  server-files-1:
    name: asa-server_server-files-1
  backups-1:
    name: asa-server_backups-1
#  steam-2:
#    name: asa-server_steam-2
#  steamcmd-2:
#    name: asa-server_steamcmd-2
#  server-files-2:
#    name: asa-server_server-files-2
#  backups-2:
#    name: asa-server_backups-2

networks:
  asa-network:
    name: asa-server_asa-network
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
      # Disable IP masquerading for multiple IP setups (uncomment if needed)
      # com.docker.network.bridge.enable_ip_masquerade: 'false'