name: Build and Push to GHCR

on:
  push:
    branches: [ main, development ]
    tags:
      - 'v*'
      - '[0-9]+.*'

permissions:
  contents: read
  packages: write

jobs:
  build-stable:
    name: Build stable (main/tags) and push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    env:
      REGISTRY: ghcr.io
      IMAGE_BASENAME: ${{ github.repository_owner }}/asa-linux-server
      VERSION: 2.0.0
      GIT_COMMIT: ${{ github.sha }}
      BUILD_DATE: ${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (stable)
        run: |
          docker build \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg GIT_COMMIT=${{ env.GIT_COMMIT }} \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            -t ghcr.io/${{ env.IMAGE_BASENAME }}:latest \
            -t ghcr.io/${{ env.IMAGE_BASENAME }}:${{ env.VERSION }} \
            .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push latest (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          DEST_BASE="${{ env.REGISTRY }}/$(echo '${{ env.IMAGE_BASENAME }}' | tr '[:upper:]' '[:lower:]')"
          echo "Pushing $DEST_BASE:latest"
          docker push "$DEST_BASE:latest"

      - name: Push version tag (only on tag refs)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          DEST_BASE="${{ env.REGISTRY }}/$(echo '${{ env.IMAGE_BASENAME }}' | tr '[:upper:]' '[:lower:]')"
          VERSION_TAG="${GITHUB_REF_NAME#v}"
          echo "Pushing $DEST_BASE:$VERSION_TAG"
          docker tag "ghcr.io/${{ env.IMAGE_BASENAME }}:latest" "$DEST_BASE:$VERSION_TAG"
          docker push "$DEST_BASE:$VERSION_TAG"

  build-development:
    name: Build development (development branch) and push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    env:
      REGISTRY: ghcr.io
      IMAGE_BASENAME: ${{ github.repository_owner }}/asa-linux-server
      VERSION: 2.0.0-dev
      GIT_COMMIT: ${{ github.sha }}
      BUILD_DATE: ${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (development)
        run: |
          docker build \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg GIT_COMMIT=${{ env.GIT_COMMIT }} \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            -t ghcr.io/${{ env.IMAGE_BASENAME }}:development \
            .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push development tag
        run: |
          DEST_BASE="${{ env.REGISTRY }}/$(echo '${{ env.IMAGE_BASENAME }}' | tr '[:upper:]' '[:lower:]')"
          echo "Pushing $DEST_BASE:development"
          docker push "$DEST_BASE:development"
